version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: game_db
    restart: always
    environment:
      POSTGRES_DB: xo_game_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  telegram-bot:
    build: .
    container_name: game_bot
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/xo_game_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
      TELEGRAM_BOT_TOKEN: 8126773585:AAFLG2ccqsigrKEC-zoY9mhXaTgZYeeeuTc
    ports:
      - "8080:8080"

volumes:
  postgres_data:
